version: '3'
services:
  db:
    image: mysql:latest
    container_name: my_mysql
    environment:
      - MYSQL_ROOT_PASSWORD:fatima
      - MYSQL_DATABASE:root
      - MYSQL_USER:fatima
      - MYSQL_PASSWORD:1235
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my_phpmyadmin
    ports:
      - "8084:80"
    depends_on:
      - db
    restart: always

volumes:
  mysql_data:
